# Generated by Django 5.1 on 2024-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_savedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_eventbrite_event',
            field=models.BooleanField(default=False),
        ),
    ]
