# Generated by Django 5.1 on 2024-10-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_seatgeekevent_remove_event_is_eventbrite_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatGeekEvent',
        ),
    ]
